### 뿌리기
#### expect : token
POST localhost:8080/distributions
X-USER-ID:123
X-ROOM-ID:test-12312
content-type: application/json

{
  "totalPrice": 3000,
  "usersCount": 3
}


### 조회
#### expect : 뿌린 시각, 뿌린 금액, 받기 완료된 금액, 받기 완료된 정보 ([받은 금액, 받은 사용자 아이디] 리스트)
#### expectException : 다른 사람의 뿌리기 건 or 유효하지 않은 token인 경우 조회 실패Exception
#GET localhost:8080/distributions/{token}
GET localhost:8080/distributions/123_test-12312_9f5b5251-864a-42e1-b777-a3a68438ef6e
X-USER-ID:123
X-ROOM-ID:test-12312


### 받기
#### expect : 받은 금액
#### expectException : 뿌린지 10분 이상의 경우 받기 실패 Exception
#PUT localhost:8080/distributions/{token}/receive
PUT localhost:8080/distributions/123_test-12312_9f5b5251-864a-42e1-b777-a3a68438ef6e/receive
X-USER-ID:1234
X-ROOM-ID:test-12312

###

